Resource "File" correctly uses scmID
updatecli/updatecli pull request #564
Opened 2022-03-10 23:06 UTC by olblak

Fix #558 

If a relative file path is provided with a scmID, then like for condition and target, we want to use the git repository directory as the file root directory

## Test

To test this pull request, I used the following updatecli configuration:

.updatecli.yaml
```
---
title: "Test Git scm"

scms:
  scenario-1:
    kind: git 
    spec:
      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
      password: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      url: "https://github.com/updatecli/experiment.git"
      branch: "main"

sources:
  scenario-1:
    name: "Scenario 1"
    kind: file
    scmID: scenario-1
    spec:
      file: README.md
      line: 1
```

```shell
updatecli diff --config updatecli.yaml
```

## Additional Information

### Tradeoff
/
### Potential improvement

/

2022-03-11 08:28 UTC, dduportal requested changes
Good catch!

Can you:
- rebase against master (to only embed the commits related to this PR). easier to review.
- Add unit test(s) to cover the new code block
?

2022-03-11 08:28 UTC, dduportal commented on pkg/plugins/resources/file/source.go
> +	}
This code block have to be associated withg a unit test :)

2022-03-11 08:28 UTC, dduportal commented on pkg/plugins/resources/file/source.go
> +	if !filepath.IsAbs(f.spec.File) {
```suggestion
        # Relative path is used when an SCM is associated with the file resource: means the file is on a remote SCM (hence relative path)
	if !filepath.IsAbs(f.spec.File) {
```

2022-03-11 18:20 UTC, dduportal commented on pkg/plugins/resources/file/source.go
> +        # Relative path is used when an SCM is associated with the file resource: means the file is on a remote SCM (hence relative path)
```suggestion
        // Relative path is used when an SCM is associated with the file resource: means the file is on a remote SCM (hence relative path)
```

My bad, E_TOO_MUCH_GROOVY

2022-03-11 19:08 UTC, olblak commented
@dduportal I had to slightly modify the test struct

2022-03-12 09:53 UTC, dduportal approved these changes
@olblak you did not "slightly change" the test struct: you fixed it as it was incorrect (I don't know how did I mess it up, but it's fix with your change). Thanks!

2022-03-12 09:53 UTC, merged

2022-03-12 12:01 UTC, olblak commented
> @olblak you did not "slightly change" the test struct: you fixed it as it was incorrect (I don't know how did I mess it up, but it's fix with your change). Thanks!

Well, you did a great job for those UT, that was just a minor mistake which to be honest confused me initially :D