Fix: Various YAML file path scenario
updatecli/updatecli pull request #846
Opened 2022-09-06 18:26 UTC by olblak

Similar to https://github.com/updatecli/updatecli/pull/845
The current PR fixes the different file path scenario for the YAML resource

## Test

To test this pull request, you can run the following commands:

```shell
cp <to_package_directory>
go test
```

## Additional Information

### Tradeoff

### Potential improvement

2022-09-06 20:56 UTC, hervelemeur requested changes

2022-09-06 20:56 UTC, hervelemeur commented on pkg/plugins/resources/yaml/source.go
> +	// To merge File path with current working dire, unless file is an http url
```suggestion
```

2022-09-06 20:56 UTC, hervelemeur commented on pkg/plugins/resources/yaml/target.go
> +		return false, files, message, fmt.Errorf("URL scheme is not supported for XML target: %q", y.spec.File)
```suggestion
		return false, files, message, fmt.Errorf("URL scheme is not supported for YAML target: %q", y.spec.File)
```

2022-09-07 06:37 UTC, olblak commented on pkg/plugins/resources/yaml/utils.go
> +	if workingDir != "" &&
That's a good suggestion, I'll implement your suggestion

2022-09-10 07:37 UTC, olblak commented
So I messed up the git history with old xml change, I first need to clean this up

2022-09-10 08:24 UTC, lemeurherve commented on pkg/plugins/resources/yaml/condition.go
> +
```suggestion
```

2022-09-10 08:25 UTC, lemeurherve commented on pkg/plugins/resources/yaml/source.go
> +	// Merge Filepath with current working dire, unless file is an http url
```suggestion
	// Merge File path with current workingDir, unless File is an HTTP URL
```

2022-09-10 08:26 UTC, lemeurherve commented on pkg/plugins/resources/yaml/utils.go
> +// joinPathwithworkingDirectoryPath To merge File path with current working dire, unless file is an http url
```suggestion
// joinPathwithworkingDirectoryPath To merge File path with current workingDir, unless file is an HTTP URL
```

2022-09-10 08:27 UTC, lemeurherve commented on pkg/plugins/resources/yaml/utils.go
> +	return filepath.Join(workingDir, fileName)
```suggestion
func joinPathWithWorkingDirectoryPath(filePath, workingDir string) string {
	if workingDir == "" ||
		filepath.IsAbs(filePath) ||
		strings.HasPrefix(filePath, "https://") ||
		strings.HasPrefix(filePath, "http://") {
		return filePath
	}

	return filepath.Join(workingDir, filePath)
```

2022-09-10 08:28 UTC, lemeurherve commented on pkg/plugins/resources/yaml/utils_test.go
> +
```suggestion
			gotResult := joinPathWithWorkingDirectoryPath(tt.fileName, tt.workingDir)
```
(nit)

2022-09-10 11:15 UTC, olblak commented
The e2e tests won't work until this PR is merged

2022-09-10 11:18 UTC, hervelemeur commented
FYI you can commit suggestions in batch ;)

2022-09-10 11:19 UTC, merged

2022-09-10 11:34 UTC, lemeurherve commented
> The e2e tests won't work until this PR is merged

Did it worked on your machine? Here and on mine it didn't: https://github.com/updatecli/updatecli/runs/8284237135?check_suite_focus=true